### ISSUE TITLE
No module named 'django.contrib.admin.templatetags.admin_static

### ISSUE THREAD

**Issue by pastorenue** [purelabs/django-bulk-admin#19]
In line 8, the import statement is obsolete now.

**Comment by hadpro24** [comment]
I have the same probleme, with django 3

**Comment by annebancroftsghost** [comment]
It looks like this was removed from django 3. Not sure what the solution is. 

```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\bulk_admin\__init__.py", line 3, in <module>
    from bulk_admin.admin import (
  File "D:\dev\repos\websites\onegoodear\site_env\lib\site-packages\bulk_admin\admin.py", line 8, in <module>
    from django.contrib.admin.templatetags.admin_static import static
ModuleNotFoundError: No module named 'django.contrib.admin.templatetags.admin_static'
```

**Comment by hadpro24** [comment]
1.  You can Use this solution :
```sh
git clone https://github.com/purelabs/django-bulk-admin.git
```
2. Copy app `bulk_admin` folder in your django project
```sh
cp -r django-bulk-admin/bulk_admin .../yourprojectpath/
```
3. You can now edit importation error : open `bulk_admin/admin.py` app folder in your project 
Remplace this line 8 to :
```python
from django.templatetags.static import static
```
